spring.application.name=ProjetApiBts
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
brevo.api.key=${BREVO_API_KEY}
logging.level.com.example.ProjetApiBts.service.EmailService=DEBUG
